### ISSUE TITLE
Couldn't open file /opt/ros/kinetic/share/hsr_meshes/meshes/torso_v0/torso.std

### ISSUE THREAD

**Issue by yani-rl-ai** [rshi159/hsr_driveby_full#1]
HI @rshi159 thank you for sharing your code. 
i am interested to learn your code, i am a HSR user, but i get an error when i execute 
 ./hsr_wrs_world_pick_and_place_full
i got this following error : 
[ INFO] [1602430416.810198746]: Loading robot model 'hsrb'...
[ERROR] [1602430416.812087122]: Error retrieving file [file:///opt/ros/kinetic/share/hsr_meshes/meshes/torso_v0/torso.std]: Couldn't open file /opt/ros/kinetic/share/hsr_meshes/meshes/torso_v0/torso.std
>>Setup Scene<<
[-0.3   0.2   0.45]
>>IK Step 1<<
[ 2.65   -1.0987  0.56  ]
>>IK Step 2<<
[-0.91763856  0.37499606 -0.58251285  0.         -0.958246    0.67344977
 -0.97403164  2.57199005]
[ 2.11428074 -0.97184923 -0.59021315  0.         -0.5655785   0.58611913
 -1.20048822 -0.15060385]
q_goal_approach valid? True
q_goal_approach valid? True
>>Check IKs<<
>>Writing to File
>>Created Base Trajectory<<
[EXOTica]: [Sum of Penetrations] World Margin: 0.03 Robot Margin: 0.01
problem with setting base orientation
[-2.1   1.2  -1.57  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
======
first pass
======
Traceback (most recent call last):
  File "./hsr_wrs_world_pick_and_place_full", line 470, in <module>
    solution, midpoint = planner.solve_aico(t_grasp_begin, t_grasp_duration, t_duration, grasp = True)
  File "./hsr_wrs_world_pick_and_place_full", line 165, in solve_aico
    q_start = problem.apply_start_state(True)
AttributeError: 'pyexotica._pyexotica.Problems.UnconstrainedTimeInd' object has no attribute 'apply_start_state'

can you help me to solve? thank you

**Comment by wxmerkt** [comment]
Hi Mohamad,
This is an error in the `hsr_description` package. A patch is open upstream: https://github.com/ToyotaResearchInstitute/hsr_description/pull/9. If you build the HSR description package with this PR change locally it should work.

The second error seems like it could be from a different Exotica version. Which one did you install? You might have to build from source as well.

Best wishes,
Wolfgang
